launch:
  tag: chitubench-wan21-13b-parallel
  num_nodes: 1
  gpus_per_node: 1
  python_script: ChituBench/scripts/wan_video_benchmark.py
  srun:
    partition: debug
    cpus_per_gpu: 24
    job_name: chitubench-wan21-13b-parallel

runtime:
  chitu_debug: true
  cuda_launch_blocking: false

model:
  name: Wan2.1-T2V-1.3B
  ckpt_dir: /home/chenyy/WORK/models/Wan2.1-T2V-1.3B

parallel:
  cfp: 1
  up: 1

infer:
  attn_type: flash
  low_mem_level: 0

eval:
  eval_type: []
  reference_path: null

output:
  root_dir: ChituBench/results/wan2_1_t2v_1_3b_parallel_dit
  run_log: false
  memory: true
  timer: true
  log_ranks: [0]

overrides: []
