"""Model-independent Elastic Parallel Execution engine."""

from .api import DiffusersEPEPipeline
from .contracts import (
    ContextParallelPlan,
    DiffusionBackendFactory,
    DiffusionBackendProtocol,
    EmbeddedRuntimeConfig,
    EmbeddedRuntimeHealth,
    ExecutorBuildContext,
    ImageDecodeCompletion,
    LaneSnapshot,
    ModelParallelPlan,
    StageWorldSpec,
    TerminalArtifact,
    TransferBundle,
    VaeParallelPlan,
    normalize_terminal_artifact,
)
from .executor import DiffusersBackend
from .optimization import (
    CachedPrediction,
    DenoiseOptimization,
    DenoiseOptimizationFactory,
    ModelStepContext,
    OptimizationChain,
)
from .request import (
    DiffusionRequest,
    DiffusionResult,
    RequestMetrics,
    RequestSnapshot,
    RequestStatus,
    StructuredError,
)
from .runtime.coordinator import LaneLease, LaneReport, PulseCoordinator, PulsePlan
from .runtime.lane_broker import PulseLaneBroker
from .runtime.timeline import RankTimelineRecorder
from .runtime.worker import LaneTask, LaneWorker, LaneWorkHooks, StepOutcome
from .runtime.worker_pool import (
    AsyncResultChannel,
    DistributedRankExchange,
    FullWorldLaneWorkerPool,
    LaneWorkItem,
    LaneWorkResult,
    RankExchange,
    SingletonLaneWorkerPool,
)
from .scheduling.cost import (
    CalibratedStepCostModel,
    MeasuredStepCostModel,
    MeasuredTransferCostModel,
    RuntimeCostCalibrator,
)
from .scheduling.planner import EpePhaseAssignment, EpeRequest, EpeSchedulingModule
from .scheduling.policy import EpeSchedulingPolicy
from .scheduling.types import (
    LaneConstraints,
    RequestProfile,
    RoundRobinPolicy,
    SchedulableRequest,
    ScheduleStrategy,
    SchedulingPolicy,
    StepPlan,
)
from .trace_simulator import (
    EpeTraceSimulator,
    TraceAblationMode,
    TracePhase,
    TraceRequest,
    TraceRequestResult,
    TraceSimulationResult,
    apply_isolated_p95_deadlines,
    compare_epe_to_static_cp,
    generate_profile_trace,
    generate_variable_trace,
    load_trace,
    load_warmup_models,
    measure_isolated_baseline,
    normalize_trace_load,
    run_slo_baseline_sweep,
    save_trace,
)

__all__ = [
    "AsyncResultChannel",
    "CachedPrediction",
    "CalibratedStepCostModel",
    "DenoiseOptimization",
    "DenoiseOptimizationFactory",
    "DiffusersEPEPipeline",
    "DiffusersBackend",
    "DiffusionRequest",
    "DiffusionResult",
    "DistributedRankExchange",
    "EpeSchedulingPolicy",
    "EpeSchedulingModule",
    "EpeTraceSimulator",
    "TraceAblationMode",
    "ContextParallelPlan",
    "EpePhaseAssignment",
    "EpeRequest",
    "ModelParallelPlan",
    "VaeParallelPlan",
    "EmbeddedRuntimeConfig",
    "EmbeddedRuntimeHealth",
    "ExecutorBuildContext",
    "DiffusionBackendProtocol",
    "DiffusionBackendFactory",
    "FullWorldLaneWorkerPool",
    "ImageDecodeCompletion",
    "LaneSnapshot",
    "LaneConstraints",
    "LaneLease",
    "LaneReport",
    "LaneTask",
    "LaneWorker",
    "LaneWorkHooks",
    "LaneWorkItem",
    "LaneWorkResult",
    "MeasuredStepCostModel",
    "MeasuredTransferCostModel",
    "ModelStepContext",
    "OptimizationChain",
    "PulseCoordinator",
    "PulseLaneBroker",
    "PulsePlan",
    "RequestMetrics",
    "RequestProfile",
    "RequestSnapshot",
    "RequestStatus",
    "RankExchange",
    "RankTimelineRecorder",
    "RoundRobinPolicy",
    "RuntimeCostCalibrator",
    "SchedulableRequest",
    "SchedulingPolicy",
    "ScheduleStrategy",
    "StepPlan",
    "StepOutcome",
    "StageWorldSpec",
    "SingletonLaneWorkerPool",
    "StructuredError",
    "TerminalArtifact",
    "TransferBundle",
    "TracePhase",
    "TraceRequest",
    "TraceRequestResult",
    "TraceSimulationResult",
    "apply_isolated_p95_deadlines",
    "compare_epe_to_static_cp",
    "generate_profile_trace",
    "generate_variable_trace",
    "measure_isolated_baseline",
    "normalize_trace_load",
    "run_slo_baseline_sweep",
    "load_trace",
    "load_warmup_models",
    "normalize_terminal_artifact",
    "save_trace",
]
