launch:
  tag: chitubench-flux1-sp-usp-r2u2-4gpu
  num_nodes: 1
  gpus_per_node: 4
  python_script: ChituBench/scripts/flux_image_benchmark.py
  srun:
    partition: debug
    cpus_per_gpu: 24
    job_name: chitubench-flux1-sp-usp-r2u2-4gpu
runtime:
  chitu_debug: true
  cuda_launch_blocking: false
model:
  name: Flux1-dev
  ckpt_dir: /home/chenyy/WORK/models/Flux-1
parallel:
  cfp: 1
  up: 2
infer:
  attn_type: flash
  low_mem_level: 0
eval:
  eval_type: []
  reference_path: null
output:
  root_dir: ChituBench/results/flux1_dev_sequence_parallel
  run_log: false
  memory: false
  timer: true
  log_ranks:
  - 0
overrides: []
