name: FLUX.2-klein-4B
type: flux2-klein
source: "https://huggingface.co/black-forest-labs/FLUX.2-klein-4B" # Just for displaying. No automatic download.
ckpt_dir: null # Please override this in command line with `models.ckpt_dir=<path>`.
transformer_checkpoint: "transformer"
tokenizer_path: null # By default the same as ckpt_dir, or you can override it with `models.tokenizer_path:<path>`.
tokenizer_type: "hf" # one of: hf, tiktoken

task: t2i

encoder:
  name: "qwen3"
  max_sequence_length: 512
  hidden_states_layers: [9, 18, 27]

vae:
  checkpoint: "vae"
  scale_factor: 8

sampler:
  sample_steps: 4
  guidance_scale: [1.0]
  boundary: []
  num_train_timesteps: 1000

transformer:
  in_channels: 128
  out_channels: null
  num_layers: 5
  num_single_layers: 20
  attention_head_dim: 128
  num_attention_heads: 24
  joint_attention_dim: 7680
  timestep_guidance_channels: 256
  mlp_ratio: 3.0
  axes_dims_rope: [32, 32, 32, 32]
  rope_theta: 2000
  eps: 1e-6
  guidance_embeds: false
